### ISSUE TITLE
 Link to an unreachable site

### ISSUE THREAD

**Issue by PatrykMie** [TYPO3-Documentation/TYPO3CMS-Guide-Installation#233] opened 2021-07-15 09:43 UTC
On the following page https://docs.typo3.org/m/typo3/guide-installation/master/en-us/QuickInstall/Index.html in the first point there is a link to an unreachable page "DDEV" https://www.ddev.com/get-started/.

**Comment by susannemoog** [comment] 2021-07-28 09:48
Thank you for reporting this issue. The link you mentioned is working now. It was probably caused by a temporary outage on the ddev site. I'm going to close this issue now, thanks again.

**Closed by susannemoog** 2021-07-28 09:48 UTC
